proc import datafile = "/folders/myfolders/Score_Month1" 
DBMS = xlsx out = SCORE_MONTH1 replace;
run; 

proc import datafile = "/folders/myfolders/Score_Month2" 
DBMS = xlsx out = SCORE_MONTH2 replace;
run;

PROC SQL;
TITLE 'UNION';
SELECT * FROM SCORE_MONTH1
UNION
SELECT * FROM SCORE_MONTH2;


PROC SQL;
TITLE 'EXCEPT';
SELECT * FROM SCORE_MONTH1
EXCEPT
SELECT * FROM SCORE_MONTH2;

PROC SQL;
TITLE 'INTERSECT';
SELECT * FROM SCORE_MONTH1
INTERSECT
SELECT * FROM SCORE_MONTH2;

PROC SQL;
TITLE 'OUTER UNION';
SELECT * FROM SCORE_MONTH1
OUTER UNION
SELECT * FROM SCORE_MONTH2;

PROC SQL;
TITLE 'OUTER UNION CORR';
SELECT * FROM SCORE_MONTH1;
OUTER UNION CORR
SELECT * FROM SCORE_MONTH2;